Books/Controllers/DropDownController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Books.DataAccess;
using Books.Helper;
using BootstrapMvcSample.Controllers;

namespace Books.Controllers
{
    public class DropDownController : BootstrapBaseController
    {
        public DropDownController(BooksDbContext context, ISessionState sessionstate)
            : base(context, sessionstate)
        {
        }

        public ActionResult GetStatuses(string selectedId)
        {
            ViewData.Model = _context.Statuses.Select(c=>new SelectListItem()
                                    {
                                        Value = c.Status,
                                        Text = c.Status,
                                        Selected = selectedId==c.Status
                                    }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Status") { NullDisplayText = " выберите статус" };
            return View("Dropdown");
        }

        public ActionResult GetOrderTypes(string selectedId)
        {
            ViewData.Model = _context.OrderTypes.Select(c=>new SelectListItem()
                                    {
                                        Value = c.OrderType,
                                        Text = c.OrderType,
                                        Selected = selectedId==c.OrderType
                                    }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "OrderType") { NullDisplayText = " выберите Тип заказа" };
            return View("Dropdown");
        }

        public ActionResult GetFormats(string selectedId)
        {
            ViewData.Model = _context.Formats.Select(c=>new SelectListItem()
                                    {
                                        Value = c.Format,
                                        Text = c.Format,
                                        Selected = selectedId==c.Format
                                    }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Format") { NullDisplayText = " выберите Носитель" };
            return View("Dropdown");
        }

        public ActionResult GetCurrencies(string selectedId)
        {
            ViewData.Model = _context.Currencies.Select(c=>new SelectListItem()
                                    {
                                        Value = c.Currency,
                                        Text = c.Currency,
                                        Selected = selectedId==c.Currency
                                    }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Currency") { NullDisplayText = " выберите валюту " };
            return View("Dropdown");
        }

        public ActionResult GetBibTypes(string selectedId)
        {
            ViewData.Model = _context.BibTypes.Select(c => new SelectListItem()
            {
                Value = c.BibType,
                Text = c.BibType,
                Selected = selectedId == c.BibType
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "BibType") { NullDisplayText = " выберите тип записи" };
            return View("Dropdown");
        }
        public ActionResult GetSizes(string selectedId)
        {
            //9. Формат -- выпадающий списко из двух значений А4 и А3
            var values = new[] {"A4", "A3"};
            ViewData.Model = values.Select(c => new SelectListItem()
            {
                Value = c,
                Text = c,
                Selected = selectedId == c
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Size") { NullDisplayText = " выберите формат" };
            return View("Dropdown");
        }
        public ActionResult GetUsers(string selectedId)
        {
            ViewData.Model = _context.UserProfiles.Select(c => new SelectListItem()
            {
                Value = c.UserName,
                Text = c.UserName,
                Selected = selectedId == c.UserName
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "User") { NullDisplayText = " выберите пользователя" };
            return View("Dropdown");
        }

        public ActionResult GetChecks(int selectedId)
        {
            ViewData.Model = _context.Checks.Select(inv => inv.Id).ToList().Select(c => new SelectListItem()
            {
                Value = c.ToString(),
                Text = c.ToString(),
                Selected = selectedId == c
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Check") { NullDisplayText = " выберите чек" };
            return View("Dropdown");
        }

        public ActionResult GetContracts(int selectedId)
        {
            ViewData.Model = _context.Contracts.ToList().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Id.ToString()+(c.Date.HasValue?" от "+c.Date.Value.ToShortDateString():"")+" "+c.Partner,
                Selected = selectedId == c.Id
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Contract") { NullDisplayText = " выберите договор" };
            return View("Dropdown");
        }

        public ActionResult GetInvoices(int selectedId)
        {
            ViewData.Model = _context.Invoices.Select(inv=>inv.Id).ToList().Select(c => new SelectListItem()
            {
                Value = c.ToString(),
                Text = c.ToString(),
                Selected = selectedId == c
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Invoice") { NullDisplayText = " выберите счет" };
            return View("Dropdown");
        }

        public ActionResult GetRoles(string selectedId)
        {
            ViewData.Model = Roles.GetAllRoles().Select(c => new SelectListItem()
            {
                Value = c,
                Text = c,
                Selected = selectedId == c
            }).ToList();

            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(string),
                    "Role") { NullDisplayText = " выберите роль" };
            return View("Dropdown");
        }
            //HasOptional(a => a.Invoices).WithMany(b => b.Works).HasForeignKey(c => c.Invoice); // FK_works_invoice
            //HasOptional(a => a.Contracts).WithMany(b => b.Works).HasForeignKey(c => c.Contract); // FK_works_contract
            //HasOptional(a => a.Checks).WithMany(b => b.Works).HasForeignKey(c => c.Check); // FK_works_check
            //HasOptional(a => a.Acts).WithMany(b => b.Works).HasForeignKey(c => c.Act); // FK_works_act
    }

}

Books/Controllers/TypeAheadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Books.DataAccess;
using Books.Helper;
using BootstrapMvcSample.Controllers;

namespace Books.Controllers
{
    public class TypeAheadController : BootstrapBaseController
    {
        public TypeAheadController(BooksDbContext context, ISessionState sessionstate)
            : base(context, sessionstate)
        {
        }
        public class Options
        {
            public IEnumerable<string> options;
        }
        public ActionResult Library(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Library.StartsWith(query)).Select(w => w.Library).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Publisher(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Publisher.StartsWith(query)).Select(w => w.Publisher).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Journal(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Journal.StartsWith(query)).Select(w => w.Journal).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Theme(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Theme.StartsWith(query)).Select(w => w.Theme).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Author(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Author.StartsWith(query)).Select(w => w.Author).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Editor(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Editor.StartsWith(query)).Select(w => w.Editor).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Seller(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Seller.StartsWith(query)).Select(w => w.Seller).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Address(string query)
        {
            var result = new Options();
            result.options = _context.Works.Where(w => w.Address.StartsWith(query)).Select(w => w.Address).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Shop(string query)
        {
            var result = new Options();
            result.options = _context.Invoices.Where(w => w.Shop.StartsWith(query)).Select(w => w.Shop).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Agency(string query)
        {
            var result = new Options();
            result.options = _context.Checks.Where(w => w.Agency.StartsWith(query)).Select(w => w.Agency).Distinct().ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        
    }
}

Books/Views/Shared/EditorTemplates/AddressTypeAhead.cshtml
@model string 
@Html.TextBox("Address", Model, new Dictionary<string, object>() { { "class", "input-xlarge ajax-typeahead" }, {"data-link", Url.Action("Address", "TypeAhead") }})

Books/Views/Shared/EditorTemplates/ChecksDropDown.cshtml
@{ Html.RenderAction("GetChecks", "DropDown", new { selectedId = Model??0 }); 
   if (Model != null)
   {
       <a href="@Url.Action("Edit","Checks", new {id=Model})">чек @Model</a>
   }
   else
   {
       <a href="@Url.Action("Create","Checks")">новый чек</a>
   }
}

Books/Views/Shared/EditorTemplates/ContractsDropDown.cshtml
@{ Html.RenderAction("GetContracts", "DropDown", new { selectedId = Model??0 }); 
   if (Model != null)
   {
       <a href="@Url.Action("Edit","Contracts", new {id=Model})">договор @Model</a>
   }   
   else
   {
       <a href="@Url.Action("Create","Contracts")">новый договор</a>
   }
}

Books/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@Html.TextBox("", (Model.HasValue ? Model.Value.ToShortDateString() : string.Empty), new { @class = "datePicker", data_val="false" })

Books/Views/Shared/EditorTemplates/InvoicesDropDown.cshtml
@{ Html.RenderAction("GetInvoices", "DropDown", new { selectedId = Model??0 }); 
   if (Model != null)
   {
       <a href="@Url.Action("Edit","Invoices", new {id=Model})">счет @Model</a>
   }   
   else
   {
       <a href="@Url.Action("Create","Invoices")">новый счет</a>
   }
}

Books/Views/Shared/EditorTemplates/JournalTypeAhead.cshtml
@model string 
@Html.TextBox("Journal", Model, new Dictionary<string, object>() { { "class", "input-xlarge ajax-typeahead" }, {"data-link", Url.Action("Journal", "TypeAhead") }})

Books/Views/Shared/EditorTemplates/LibraryTypeAhead.cshtml
@model string 
@Html.TextBox("Library", Model, new Dictionary<string, object>() { { "class", "input-xlarge ajax-typeahead" }, {"data-link", Url.Action("Library", "TypeAhead") }})

Books/Views/Shared/EditorTemplates/OrderTypesDropDown.cshtml
@{ Html.RenderAction("GetOrderTypes", "DropDown", new { selectedId = Model??""  }); }

Books/Views/Shared/EditorTemplates/RolesDropDown.cshtml
@{ Html.RenderAction("GetRoles", "DropDown", new { selectedId = Model??""  }); }

Books/Views/Shared/EditorTemplates/SellersTypeAhead.cshtml
@model string 
@Html.TextBox("Seller", Model, new Dictionary<string, object>() { { "class", "input-xlarge ajax-typeahead" }, {"data-link", Url.Action("Seller", "TypeAhead") }})

Books/Views/Shared/EditorTemplates/ShopsTypeAhead.cshtml
@model string 
@Html.TextBox("Shop", Model, new Dictionary<string, object>() { { "class", "input-xlarge ajax-typeahead" }, {"data-link", Url.Action("Shop", "TypeAhead") }})

Books/Views/Shared/EditorTemplates/SizesDropDown.cshtml
@{ Html.RenderAction("GetSizes", "DropDown", new { selectedId = Model??""  }); }

Books/Views/Shared/EditorTemplates/StatusesDropDown.cshtml
@{ Html.RenderAction("GetStatuses", "DropDown", new { selectedId = Model??""  }); }

Books/Views/Shared/EditorTemplates/UsersDropDown.cshtml
@{ Html.RenderAction("GetUsers", "DropDown", new { selectedId = Model??""  }); }